
loading Tensorflow

loading scikit-learn

Upgrade pip, install requirements, upgrade pandas
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/ddeq/.local/lib/python3.8/site-packages (23.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cuda-python in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (12.1.0)
Requirement already satisfied: tensorboardX in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.6)
Requirement already satisfied: psutil in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (5.7.2)
Requirement already satisfied: opencv-python in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (4.2.0.32)
Requirement already satisfied: Pillow in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (8.3.1)
Requirement already satisfied: matplotlib in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (3.4.3)
Requirement already satisfied: carbontracker in /home/ddeq/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (1.1.7)
Collecting pandas>=1.3.0 (from -r requirements.txt (line 8))
  Using cached pandas-2.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
Requirement already satisfied: cython in /home/ddeq/.local/lib/python3.8/site-packages (from cuda-python->-r requirements.txt (line 1)) (0.29.24)
Requirement already satisfied: numpy in /opt/itu/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages (from tensorboardX->-r requirements.txt (line 2)) (1.19.4)
Requirement already satisfied: packaging in /home/ddeq/.local/lib/python3.8/site-packages (from tensorboardX->-r requirements.txt (line 2)) (21.0)
Requirement already satisfied: protobuf<4,>=3.8.0 in /opt/itu/easybuild/software/protobuf-python/3.14.0-GCCcore-10.2.0/lib/python3.8/site-packages (from tensorboardX->-r requirements.txt (line 2)) (3.14.0)
Requirement already satisfied: cycler>=0.10 in /home/ddeq/.local/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ddeq/.local/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 6)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/ddeq/.local/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 6)) (2.8.2)
Requirement already satisfied: requests in /home/ddeq/.local/lib/python3.8/site-packages (from carbontracker->-r requirements.txt (line 7)) (2.26.0)
Requirement already satisfied: geocoder in /home/ddeq/.local/lib/python3.8/site-packages (from carbontracker->-r requirements.txt (line 7)) (1.38.1)
Requirement already satisfied: pynvml in /home/ddeq/.local/lib/python3.8/site-packages (from carbontracker->-r requirements.txt (line 7)) (11.5.0)
Requirement already satisfied: importlib-metadata in /home/ddeq/.local/lib/python3.8/site-packages (from carbontracker->-r requirements.txt (line 7)) (4.6.4)
Requirement already satisfied: pytz>=2020.1 in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from pandas>=1.3.0->-r requirements.txt (line 8)) (2020.1)
Requirement already satisfied: tzdata>=2022.1 in /home/ddeq/.local/lib/python3.8/site-packages (from pandas>=1.3.0->-r requirements.txt (line 8)) (2023.3)
Collecting numpy (from tensorboardX->-r requirements.txt (line 2))
  Using cached numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Requirement already satisfied: six in /home/ddeq/.local/lib/python3.8/site-packages (from cycler>=0.10->matplotlib->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: click in /home/ddeq/.local/lib/python3.8/site-packages (from geocoder->carbontracker->-r requirements.txt (line 7)) (8.0.1)
Requirement already satisfied: future in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from geocoder->carbontracker->-r requirements.txt (line 7)) (0.18.2)
Requirement already satisfied: ratelim in /home/ddeq/.local/lib/python3.8/site-packages (from geocoder->carbontracker->-r requirements.txt (line 7)) (0.1.6)
Requirement already satisfied: zipp>=0.5 in /home/ddeq/.local/lib/python3.8/site-packages (from importlib-metadata->carbontracker->-r requirements.txt (line 7)) (3.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ddeq/.local/lib/python3.8/site-packages (from requests->carbontracker->-r requirements.txt (line 7)) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/ddeq/.local/lib/python3.8/site-packages (from requests->carbontracker->-r requirements.txt (line 7)) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ddeq/.local/lib/python3.8/site-packages (from requests->carbontracker->-r requirements.txt (line 7)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ddeq/.local/lib/python3.8/site-packages (from requests->carbontracker->-r requirements.txt (line 7)) (3.2)
Requirement already satisfied: decorator in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from ratelim->geocoder->carbontracker->-r requirements.txt (line 7)) (4.4.2)
Installing collected packages: numpy, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.0.0 requires PyYAML, which is not installed.
albumentations 1.0.0 requires scikit-image>=0.16.1, which is not installed.
imgaug 0.4.0 requires imageio, which is not installed.
imgaug 0.4.0 requires scikit-image>=0.14.2, which is not installed.
Successfully installed numpy-1.21.2 pandas-2.0.0
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /opt/itu/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages (1.1.4)
Collecting pandas
  Using cached pandas-2.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ddeq/.local/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/itu/easybuild/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: tzdata>=2022.1 in /home/ddeq/.local/lib/python3.8/site-packages (from pandas) (2023.3)
Collecting numpy>=1.20.3 (from pandas)
  Using cached numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Requirement already satisfied: six>=1.5 in /home/ddeq/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: numpy, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.0.0 requires PyYAML, which is not installed.
albumentations 1.0.0 requires scikit-image>=0.16.1, which is not installed.
imgaug 0.4.0 requires imageio, which is not installed.
imgaug 0.4.0 requires scikit-image>=0.14.2, which is not installed.
Successfully installed numpy-1.21.2 pandas-2.0.0
Pandas version: 1.1.4

Making pcam-small dataframe
2023-04-17 16:31:59.162412: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "src/make_dataframe.py", line 14, in <module>
    dataframe = collect_data(home, args.dataset)
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 466, in collect_data
    dataframe = import_PCAM(data_dir, target_data)
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 185, in import_PCAM
    dataframe = pd.concat(
  File "/opt/itu/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 274, in concat
    op = _Concatenator(
  File "/opt/itu/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
